;;  This file is part of the arc package
;;  Copyright (C) 2002, 2003, 2009 by Gregor Klinke
;;
;;  This library is free software: you can redistribute it and/or modify
;;  it under the terms of the GNU Lesser General Public License as published
;;  by the Free Software Foundation, either version 3 of the License, or
;;  (at your option) any later version.
;;
;;  This library is distributed in the hope that it will be useful,
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;  GNU Lesser General Public License for more details.
;;
;;  You should have received a copy of the GNU General Public License
;;  along with this program.  If not, see <http://www.gnu.org/licenses/>.

(arc:provide 'task-c-compile-linux)

(arc:log 'debug "loading 'c-compile' task [linux]")

(arc:require 'task-c-compile-gcc "generic/task-c-compile-gcc")


;; backend functionality for compilation and c file dependency control on
;; linux systems.  Since linux system comes by default with the gcc
;; compiler, this class assumes gcc compilation.  C-file dependencies are
;; generated by gcc too, so there's no need for a special class here.
(define <arc:c-compile-linux>
  (arc:make-class 
   '<arc:c-compile-linux>               ; name of the class
   <arc:c-compile-gcc>                  ; super class
   '()                                  ; slots
   
   ;; methods
   `(
     (shared-obj-flag ,(lambda (self) "-fpic -DPIC -dynamic"))
     )))


;;Keep this comment at the end of the file 
;;Local variables:
;;mode: scheme
;;End:

