;;  This file is part of the arc package
;;  Copyright (C) 2009 by Gregor Klinke
;;
;;  This library is free software; you can redistribute it and/or modify it
;;  under the terms of the GNU Lesser General Public License as published
;;  by the Free Software Foundation; either version 2.1 of the License, or
;;  (at your option) any later version.
;;
;;  This library is distributed in the hope that it will be useful, but
;;  WITHOUT ANY WARRANTY; without even the implied warranty of
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;  Lesser General Public License for more details.
;;
;;  You should have received a copy of the GNU Lesser General Public
;;  License along with this library; if not, write to the Free Software
;;  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

;; $Id: task-c-compile-darwin.scm,v 1.1 2009/03/14 23:40:20 eyestep Exp $


(arc:provide 'task-c-compile-darwin)

(arc:log 'debug "loading 'c-compile' task [darwin]")

(arc:require 'task-c-compile-gcc "generic/task-c-compile-gcc")


;; backend functionality for compilation and c file dependency control on
;; darwin systems (incl. Mac OSX).  Since on Darwin/MacOSX the default
;; compiler is the gcc compiler, this class assumes gcc compilation.
;; C-file dependencies are generated by gcc, too, so there's no need for a
;; special class here.
(define <arc:c-compile-darwin>
  (arc:make-class 
   '<arc:c-compile-darwin>              ; name of the class
   <arc:c-compile-gcc>                  ; super class
   '()                                  ; slots
   
   ;; methods
   `(
     (shared-obj-flag ,(lambda (self) "-fPIC -dynamic"))
     )))


;;Keep this comment at the end of the file 
;;Local variables:
;;mode: scheme
;;End:

